// "use client";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import ChatBot from "@/components/Chatbot/ChatBot";
// import { usePathname } from "next/navigation";
// import { useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "Daftar Route",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pathname = usePathname();
  // const [loading, setLoading] = useState(false);

  // useEffect(() => {
  //   setLoading(true);
  //   const timer = setTimeout(() => setLoading(false), 700);
  //   return () => clearTimeout(timer);
  // }, [pathname]);
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={{ margin: 0, padding: 0 }}>

        <Header />
        {/* {loading && (
          <div className="loader-wrapper">
            <div className="loader"></div>
          </div>
        )} */}
        {children}
        <Footer />
        <ChatBot />
      </body>
    </html>
  );
}
