
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import ChatBot from "@/components/Chatbot/ChatBot";
export const metadata: Metadata = {
  title: "Daftar Route",
  description: "Generated by create next app",
};

// src/app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={{margin:"0"}}>
        
    <Header />
       
        
        <div
          className="body-container"
          style={{ marginLeft: "120px", marginRight: "120px" }}
        >
          {children}
        </div>
        <Footer />
        <ChatBot />
      </body>
    </html>
  );
}
